env:
  - GO111MODULE=on

before:
  hooks:
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0

    binary: packer-builder-vultr

    asmflags:
      - -D mysymbol
      - all=-trimpath={{.Env.GOPATH}}

    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
      - ./dontoptimizeme=-N

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - 386

archives:
  -
    replacements:
      darwin: macOs
      linux: linux
      windows: windows
      386: 32-bit
      amd64: 64-bit

    format: tar.gz

    files:
      - none*

    format_overrides:
      - goos: windows
        format: zip


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .ProjectName }}_v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: ddymko
    name: packer-builder-vultr