name: Nightly Acceptance
on:
  schedule:
    - cron: '*/10 * * * *' # run at 2 AM UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - run: make test